### ISSUE TITLE
register data during preprocessing

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/microDL#185] opened 2022-11-09 05:56 UTC
Pixel-precise registration is essential for virtual staining. Correlative label-free/fluorescence datasets are sometimes not registered due to shifts introduced by the dichroic mirror or chromatic aberrations among imaged wavelengths. The data across multiple positions and time points may also drift.

 We have a [script](https://github.com/mehta-lab/microDL/blob/main/scripts/align_z_focus.py) to register data saved as single-page tiff.

We need a script to register channels in zarr stores produced by recOrder. 
We did consider adding such registration to recOrder, however, we may need to align data across multiple positions for virtual staining, which is not within the scope of recOrder.

**Comment by mattersoflight** [comment] 2022-11-09 05:58
@jennyfolkesson registration can be a step in preprocessing (along with flat fielding and masking) in #172.

**Comment by jennyfolkesson** [comment] 2022-11-14 18:56
@mattersoflight sure, it can be added to preprocessing with zarr support, which we'll have once https://github.com/mehta-lab/microDL/pull/172 is merged to main.
Instead of creating links with new z indices we'll probably write a "start z" of some kind in the zarr metadata for each position.

Question: the parameters that are hardcoded, should they be the input parameters (i.e. added to config)? https://github.com/mehta-lab/microDL/blob/main/scripts/align_z_focus.py#L172

**Comment by Christianfoley** [comment] 2022-11-16 02:06
> Question: the parameters that are hardcoded, should they be the input parameters (i.e. added to config)? https://github.com/mehta-lab/microDL/blob/main/scripts/align_z_focus.py#L172

I think these parameters might vary from dataset to dataset depending on imaging conditions. @Soorya19Pradeep have you had to change these parameters between experiments?

**Comment by JohannaRahm** [comment] 2022-11-21 15:30
Yes they definitely vary between experiments and it is a good idea to have them as input parameters in the config!

Depending on the experiment it makes sense to choose different reference channels from the polarization and fluorescence group as reference channels. The focus of the chosen reference channels is aligned to have the same focus idx. Differences in focus within the fluorescence channel groups are kept, which makes sense as the focus of imaged objects might lie in different planes (e.g. the membrane might have a lower focus idx as the nucleus due to the 3D shape of the cell).

The parameters `max_focus_idx` and `min_focus_idx` are set and help if there is a lot of variation in the focus-z-id, which might be caused by an unstable autofocus during experiment recording. Field of views with focus idx above or below these thresholds are filtered out at that stage. This has two advantages: (1) FOVs with strong signal at the border of volume causes phase reconstruction artifacts (2) the script at this stage aligns the chosen reference channels from the polarization and fluorescence groups. The resulting aligned FOVs have the same z-range (e.g. 20-70, with the focus at z-id 40). If there are too large differences in original z-focus-idx the z-range becomes too small.

**Comment by mattersoflight** [comment] 2022-12-05 16:45
After further discussion of how one may implement on-the-fly registration, we realized that registration is best done as a script within recOrder that depends on iohub and  waveOrder/recOrder. We need to deal with unstable autofocus during acquisition and reconstruction. It makes sense to handle focus drift once in the entire data analysis pipeline that spans acquisition -> deconvolution -> data analysis.

@edyoshikun and @talonchandler will take this forward since they will be implementing similar features for other multimodal analysis questions.

microDL 2.0.0 would expect a zarr store of well-registered data as an input.

**Comment by Soorya19Pradeep** [comment] 2023-02-17 00:41
I have successfully been able to register the channels in Z using the focus finding script @talonchandler contributed and simple registration in X and Y. This happens as a step after raw image reconstruction and the registered data is used as input to microDL pipeline. Is there any further steps to contribute to this issue?

**Closed** 2023-06-16 22:42 UTC
Labels: preprocessing
