### ISSUE TITLE
Allowing user specified masks

### ISSUE THREAD

**Issue by smguo** [mehta-lab/microDL#126] opened 2020-03-03 02:36 UTC
Parameter "mask_dir" seems to have a different meaning in `inference_dataset.py` from training and preprocessing. From the docstring:
":param str/None mask_dir: If inference targets are masks stored in a
         different directory than the image dir. Assumes the directory contains
         a frames_meta.csv containing mask channels (which will be target channels
          in the inference config) z, t, p indices matching the ones in image_dir"

It seems to me here mask_dir is actually target_dir, but in training time mask_dir refers to the folder with binary or float maps used for weighted loss calculation.

I suggest we use "target_dir" instead of "mask_dir" in `inference_dataset.py` to avoid confusion. Also separate "data_dir" into "input_dir" and "target_dir" in the training and preprocessing pipeline to be consistent to this change, since currently the input and target images are assumed to be always in the same directory.

**Comment by pranathivemuri** [comment] 2020-03-03 04:09
1. could this change wait until Jenny comes back on March 17th, it seems like a big refactor.
2. I am sure mask_dir doesn't include the float weight maps, mask_dir is always binary target, in preprocessing mask_dir is binary masks which is used to compute and combine the float weight maps created into the input_dir by setting them in a channel of the input data which is given as data_dir in the config
3. given that mask_dir is always binary masks, I don't see why we would need any change

Please correct me if I am wrong

**Comment by smguo** [comment] 2020-03-03 17:18
Yes mask_dir is always binary masks, but its role is different in segmentation and regression tasks. Here is my understanding of the role of mask_dir for segmentation and regression:
For segmentation,
mask_dir:  binary input supplied by the user; used as the target for training
weight_dir: weight maps generated by mask generator using mask_dir as input; used for computing weighted loss

For regression,
mask_dir: generated by mask generator (more common)m or supplied by the user; used for computing weighted loss (masked loss); not the target for training
weight_dir: N/A

To me the change of the role of mask_dir in different use cases is confusing. We can discuss this with Jenny after she is back. I'll leave it as it is for now for this PR

**Comment by pranathivemuri** [comment] 2020-03-03 19:58
mask_dir is always the same for segmentation or regression i.e it is optional if the user provides it, weight_dir for segmentation is not a mandatory parameter

**Comment by jennyfolkesson** [comment] 2022-12-14 19:01
I've renamed this issue from "mixed usage of mask_dir" since masks from now on will be stored along with other channels in a zarr store.

However the issue still remains that user specified masks (generated outside of microDL) as input to preprocessing would be a good feature to have. 
Prior to implementing this, specifications need to be discussed regarding what format of masks to support.

**Comment by mattersoflight** [comment] 2023-07-13 17:31
This is still relevant, but straightforward to do by updating the masks in the ome-zarr store. Closing. cc: @Soorya19Pradeep.

**Closed by mattersoflight** 2023-07-13 17:31 UTC
Labels: preprocessing
